[tools]
node = 'lts'
python = "3.12"
go = "1.25"
terraform = "1"
deno = "latest"
"go:github.com/d-kuro/gwq/cmd/gwq" = { version = "latest" }

[settings]
verbose = false

legacy_version_file = true
experimental = true

plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

trusted_config_paths = [
    '~/code/shotasenga',
]
idiomatic_version_file_enable_tools = ["python"]
